# Copyright (c) 2022 José Miguel Guerrero Hernández
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

computer_vision:
# Default position
  world: "aws_house"
#  world: "aws_small_warehouse_no_roof"
#  world: "aws_bookstore"
  tiago_position:
    x: '-x 0.0'
    y: '-y 0.0'
    z: '-z 0.0'
    roll: '-R 0.0'
    pitch: '-P 0.0'
    yaw: '-Y 0.0'

# Hospital position
#  world: "aws_hospital"
#  tiago_position:
#    x: '-x 0.0'
#    y: '-y 1.0'
#    z: '-z 0.0'
#    roll: '-R 0.0'
#    pitch: '-P 0.0'
#    yaw: '-Y 1.58'

# Racetrack position
#  world: "aws_racetrack_day_empty"
#  world: "aws_racetrack_day"
#  world: "aws_racetrack_night"
#  tiago_position:
#    x: '-x 2.75'
#    y: '-y -15.0'
#    z: '-z 0.2'
#    roll: '-R 0.0'
#    pitch: '-P 0.0'
#    yaw: '-Y 0.0'
